api-module: f

base:
  application:
    name: biz-f-service
  api:
    prefix: api
  server:
    # 是否启用，默认：true
    enable: true
    # 端口号
    port: 18005
    # web框架gin的配置
    gin:
      # 有三种模式：debug/release/test，填错则使用release
      mode: release
    response:
      print:
        # 是否打印：true, false；默认 false
        enable: true
  endpoint:
    # 配置的管理（查看和变更），默认关闭，true/false
    config:
      enable: true
    health:
      enable: true

  redis:
    enable: true
    password: ZljIsysc0re123
    standalone:
      addr: redis-service:26379

  datasource:
    username: isyscore
    password: Isysc0re
    host: mysql-service
    port: 23306
    driver-name: mysql
    db-name: isc_demo
    # 示例：charset=utf8&parseTime=True&loc=Local 等url后面的配置，直接配置即可
    url-config:
      charset: utf8
      parseTime: True
      loc: Local

  etcd:
    enable: true
    endpoints:
      - etcd-service:22379
    username: isyscore
    password: Isysc0re
    dial-timeout: 5s
  tracing:
    enable: true
    collector-endpoint: http://isc-core-back-service:31300/api/core/back/v1/middle/spans
    redis:
      enable: true
    etcd:
      enable: true
    orm:
      enable: true
